In [105]:
import pandas as pd
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

In [106]:
school_data_complete

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39165,39165,Donna Howard,F,12th,Thomas High School,99,90,14,Charter,1635,1043130
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70,14,Charter,1635,1043130
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84,14,Charter,1635,1043130
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90,14,Charter,1635,1043130
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,14,Charter,1635,1043130

In [107]:
total_schools = school_data_complete["school_name"].value_counts().count()
total_students = school_data_complete["student_name"].count()
total_budget = school_data["budget"].sum()
average_math = school_data_complete["math_score"].mean()
average_reading = school_data_complete["reading_score"].mean()
Number_Passing_Math = school_data_complete.loc[(school_data_complete["math_score"] > 69)].count()
Percent_Passing_Math = (Number_Passing_Math / total_students)*100
Number_Passing_Reading = school_data_complete.loc[(school_data_complete["reading_score"] > 69)].count()
Percent_Passing_Reading = (Number_Passing_Reading / total_students)*100
Overall_Passing_Rate = (Percent_Passing_Math+Percent_Passing_Reading)/2

In [113]:
district_summary = {"Total Schools":total_schools,"Total Students":total_students}

In [114]:
district_summary_df = pd.DataFrame(district_summary)

ValueError: If using all scalar values, you must pass an index